### ISSUE TITLE
Issue Snapshots from Master

### ISSUE THREAD

**Issue by cedrickcooke** [JuulLabs/exercise#32]
A lot of our feature prioritization is done so we can eat our own dog food. Would be nice if we didn't have to issue a release for every feature, so we could make them more meaningful.

**Comment by twyatt** [comment]
What version name should the snapshot get?

It isn't too difficult to determine the previous tag, but it would be weird to name the snapshot with the previously released version number (with `-SNAPSHOT` suffix).

By `bash`-foo isn't strong, but I could look into automatically bumping the version number. Would I bump the **minor** or **major** version number?

**Comment by cedrickcooke** [comment]
I think `master-SNAPSHOT` is totally fine as it provides an "always the latest and greatest" release train. Adding version snapshots can be something we consider later (likely after 1.0)

**Comment by twyatt** [comment]
Should I drop the existing "snapshot from branch" support?
